travis:
  secure:
    BINSTAR_TOKEN: UB7oabZRk48sD3QRMRo73dcNwv2pWFCRq0ZxV7DfGIHRgj8seTImYcR5N/nlT7bxxaPDVy6BFxAYRoG3dEwVPNezcm6asueOFTAEh5mTs/j7sN1R0JbAxr2xnAgwX+GjwXXq08cE1gSsQ3o0aJOGSvwnV282ug1vUjjfG5fLa7g26rAuyGQZS90sQiSj99sHESYID6hpiTM5TTT7MNuC4di+IZ9HkmdKBQyOs11L3QBEN2LIPskixkdpNvVJ0gM7fwSqajkrsZW3J/nO5Z2gMuoiBCz52oB1MYtZlapN2RDtoCjT1+SXUD+wy18o5feYr4PpEtEJv0B8bsKtUkm5boHjCRHrHGK9e/UE484SJ5DbFDLGazfelUuZF8liOz+pEN5zCu46C5G0trLuyAZqTWCJSFM7jNL84+DB/IGFzFoGNpsgISYLmg9PyaJ+l8E5saQ3objCSTRqiJp/Eu6CPjS2ucXjjmdhNeBrsk0B7AVVoY2jbvlrhjVWVHWzN8u1RtDs2dquByOenAahqZh3mXgIcSTI358zVzRyzKkqcxE0HWcea7DqXxf7HA4yIhL3dcX5+s8shuEZ/3ODMLa7ZYyezFGynWIHV0wQT+GAq4RvtoV0Qa4gEaAMNegzi5BnZwn739dizl/hVNvNY0lXW+mhjz0MWudXT/2i52iRw9U=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
